### ISSUE TITLE
Написать инструкцию по пользованию meet.jit.si

### ISSUE THREAD

**Issue by mike1pol** [piterjs/documents#9]
Описать как пользоваться jit.si в замену hangouts

**Comment by fogrew** [comment]
@mike1pol ты хочешь описать, как создавать созвон именно через рокет чат или просто через сайт jitsy тоже пойдёт?
Кажется, что это гипер-интуитивно, в отличие от Hangouts, где надо через ютуб заходить…

**Comment by mike1pol** [comment]
тут больше про то что-бы расписать кейс как запускать лайв на ютуб

**Comment by fogrew** [comment]
Уже [было выполнено](https://github.com/piterjs/documents/commit/3e22d1260f09a5d4fcc522ea859210863cfa6622) без упоминания задачи. Спасибо, Миша.
